#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DeliveryMacana")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertCaja(Caja instance);
    partial void UpdateCaja(Caja instance);
    partial void DeleteCaja(Caja instance);
    partial void InsertWebConf(WebConf instance);
    partial void UpdateWebConf(WebConf instance);
    partial void DeleteWebConf(WebConf instance);
    partial void InsertEstados_Pedido(Estados_Pedido instance);
    partial void UpdateEstados_Pedido(Estados_Pedido instance);
    partial void DeleteEstados_Pedido(Estados_Pedido instance);
    partial void InsertPedido(Pedido instance);
    partial void UpdatePedido(Pedido instance);
    partial void DeletePedido(Pedido instance);
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    partial void InsertPedidos_Producto(Pedidos_Producto instance);
    partial void UpdatePedidos_Producto(Pedidos_Producto instance);
    partial void DeletePedidos_Producto(Pedidos_Producto instance);
    partial void InsertFechas_Estados_Pedido(Fechas_Estados_Pedido instance);
    partial void UpdateFechas_Estados_Pedido(Fechas_Estados_Pedido instance);
    partial void DeleteFechas_Estados_Pedido(Fechas_Estados_Pedido instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::Database.Properties.Settings.Default.DeliveryMacanaConnectionStringCloud, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cliente> Clientes
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Caja> Caja
		{
			get
			{
				return this.GetTable<Caja>();
			}
		}
		
		public System.Data.Linq.Table<WebConf> WebConf
		{
			get
			{
				return this.GetTable<WebConf>();
			}
		}
		
		public System.Data.Linq.Table<Estados_Pedido> Estados_Pedidos
		{
			get
			{
				return this.GetTable<Estados_Pedido>();
			}
		}
		
		public System.Data.Linq.Table<Pedido> Pedidos
		{
			get
			{
				return this.GetTable<Pedido>();
			}
		}
		
		public System.Data.Linq.Table<Producto> Productos
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
		
		public System.Data.Linq.Table<Pedidos_Producto> Pedidos_Productos
		{
			get
			{
				return this.GetTable<Pedidos_Producto>();
			}
		}
		
		public System.Data.Linq.Table<Fechas_Estados_Pedido> Fechas_Estados_Pedidos
		{
			get
			{
				return this.GetTable<Fechas_Estados_Pedido>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clientes")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private EntitySet<Pedido> _Pedidos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    #endregion
		
		public Cliente()
		{
			this._Pedidos = new EntitySet<Pedido>(new Action<Pedido>(this.attach_Pedidos), new Action<Pedido>(this.detach_Pedidos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NChar(30)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NChar(30)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NChar(30)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NChar(30)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Pedido", Storage="_Pedidos", ThisKey="Id", OtherKey="Cliente_Id")]
		public EntitySet<Pedido> Pedidos
		{
			get
			{
				return this._Pedidos;
			}
			set
			{
				this._Pedidos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Pedidos(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Pedidos(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Caja")]
	public partial class Caja : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<decimal> _Monto_Apertura;
		
		private System.Nullable<System.DateTime> _Fecha_Apertura;
		
		private System.Nullable<decimal> _Monto_Cierre;
		
		private System.Nullable<System.DateTime> _Fecha_Cierre;
		
		private bool _Estado;
		
		private System.Nullable<decimal> _Saldo;
		
		private System.Nullable<decimal> _EfectivoCaja;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMonto_AperturaChanging(System.Nullable<decimal> value);
    partial void OnMonto_AperturaChanged();
    partial void OnFecha_AperturaChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_AperturaChanged();
    partial void OnMonto_CierreChanging(System.Nullable<decimal> value);
    partial void OnMonto_CierreChanged();
    partial void OnFecha_CierreChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_CierreChanged();
    partial void OnEstadoChanging(bool value);
    partial void OnEstadoChanged();
    partial void OnSaldoChanging(System.Nullable<decimal> value);
    partial void OnSaldoChanged();
    partial void OnEfectivoCajaChanging(System.Nullable<decimal> value);
    partial void OnEfectivoCajaChanged();
    #endregion
		
		public Caja()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto_Apertura", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Monto_Apertura
		{
			get
			{
				return this._Monto_Apertura;
			}
			set
			{
				if ((this._Monto_Apertura != value))
				{
					this.OnMonto_AperturaChanging(value);
					this.SendPropertyChanging();
					this._Monto_Apertura = value;
					this.SendPropertyChanged("Monto_Apertura");
					this.OnMonto_AperturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Apertura", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Apertura
		{
			get
			{
				return this._Fecha_Apertura;
			}
			set
			{
				if ((this._Fecha_Apertura != value))
				{
					this.OnFecha_AperturaChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Apertura = value;
					this.SendPropertyChanged("Fecha_Apertura");
					this.OnFecha_AperturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto_Cierre", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Monto_Cierre
		{
			get
			{
				return this._Monto_Cierre;
			}
			set
			{
				if ((this._Monto_Cierre != value))
				{
					this.OnMonto_CierreChanging(value);
					this.SendPropertyChanging();
					this._Monto_Cierre = value;
					this.SendPropertyChanged("Monto_Cierre");
					this.OnMonto_CierreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Cierre", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Cierre
		{
			get
			{
				return this._Fecha_Cierre;
			}
			set
			{
				if ((this._Fecha_Cierre != value))
				{
					this.OnFecha_CierreChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Cierre = value;
					this.SendPropertyChanged("Fecha_Cierre");
					this.OnFecha_CierreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit NOT NULL")]
		public bool Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saldo", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Saldo
		{
			get
			{
				return this._Saldo;
			}
			set
			{
				if ((this._Saldo != value))
				{
					this.OnSaldoChanging(value);
					this.SendPropertyChanging();
					this._Saldo = value;
					this.SendPropertyChanged("Saldo");
					this.OnSaldoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EfectivoCaja", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> EfectivoCaja
		{
			get
			{
				return this._EfectivoCaja;
			}
			set
			{
				if ((this._EfectivoCaja != value))
				{
					this.OnEfectivoCajaChanging(value);
					this.SendPropertyChanging();
					this._EfectivoCaja = value;
					this.SendPropertyChanged("EfectivoCaja");
					this.OnEfectivoCajaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WebConf")]
	public partial class WebConf : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _NombreComercial;
		
		private string _TelefonoContacto;
		
		private string _Domicilio;
		
		private string _HorarioAtencion;
		
		private string _Descripcion;
		
		private bool _PublicarCatalago;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreComercialChanging(string value);
    partial void OnNombreComercialChanged();
    partial void OnTelefonoContactoChanging(string value);
    partial void OnTelefonoContactoChanged();
    partial void OnDomicilioChanging(string value);
    partial void OnDomicilioChanged();
    partial void OnHorarioAtencionChanging(string value);
    partial void OnHorarioAtencionChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnPublicarCatalagoChanging(bool value);
    partial void OnPublicarCatalagoChanged();
    #endregion
		
		public WebConf()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreComercial", DbType="NChar(80)")]
		public string NombreComercial
		{
			get
			{
				return this._NombreComercial;
			}
			set
			{
				if ((this._NombreComercial != value))
				{
					this.OnNombreComercialChanging(value);
					this.SendPropertyChanging();
					this._NombreComercial = value;
					this.SendPropertyChanged("NombreComercial");
					this.OnNombreComercialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoContacto", DbType="NChar(80)")]
		public string TelefonoContacto
		{
			get
			{
				return this._TelefonoContacto;
			}
			set
			{
				if ((this._TelefonoContacto != value))
				{
					this.OnTelefonoContactoChanging(value);
					this.SendPropertyChanging();
					this._TelefonoContacto = value;
					this.SendPropertyChanged("TelefonoContacto");
					this.OnTelefonoContactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Domicilio", DbType="NChar(80)")]
		public string Domicilio
		{
			get
			{
				return this._Domicilio;
			}
			set
			{
				if ((this._Domicilio != value))
				{
					this.OnDomicilioChanging(value);
					this.SendPropertyChanging();
					this._Domicilio = value;
					this.SendPropertyChanged("Domicilio");
					this.OnDomicilioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HorarioAtencion", DbType="NChar(80)")]
		public string HorarioAtencion
		{
			get
			{
				return this._HorarioAtencion;
			}
			set
			{
				if ((this._HorarioAtencion != value))
				{
					this.OnHorarioAtencionChanging(value);
					this.SendPropertyChanging();
					this._HorarioAtencion = value;
					this.SendPropertyChanged("HorarioAtencion");
					this.OnHorarioAtencionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublicarCatalago", DbType="Bit NOT NULL")]
		public bool PublicarCatalago
		{
			get
			{
				return this._PublicarCatalago;
			}
			set
			{
				if ((this._PublicarCatalago != value))
				{
					this.OnPublicarCatalagoChanging(value);
					this.SendPropertyChanging();
					this._PublicarCatalago = value;
					this.SendPropertyChanged("PublicarCatalago");
					this.OnPublicarCatalagoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estados_Pedidos")]
	public partial class Estados_Pedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Estado_Id;
		
		private string _Descripcion;
		
		private EntitySet<Fechas_Estados_Pedido> _Fechas_Estados_Pedidos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEstado_IdChanging(int value);
    partial void OnEstado_IdChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public Estados_Pedido()
		{
			this._Fechas_Estados_Pedidos = new EntitySet<Fechas_Estados_Pedido>(new Action<Fechas_Estados_Pedido>(this.attach_Fechas_Estados_Pedidos), new Action<Fechas_Estados_Pedido>(this.detach_Fechas_Estados_Pedidos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Estado_Id
		{
			get
			{
				return this._Estado_Id;
			}
			set
			{
				if ((this._Estado_Id != value))
				{
					this.OnEstado_IdChanging(value);
					this.SendPropertyChanging();
					this._Estado_Id = value;
					this.SendPropertyChanged("Estado_Id");
					this.OnEstado_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estados_Pedido_Fechas_Estados_Pedido", Storage="_Fechas_Estados_Pedidos", ThisKey="Estado_Id", OtherKey="Estado_Id")]
		public EntitySet<Fechas_Estados_Pedido> Fechas_Estados_Pedidos
		{
			get
			{
				return this._Fechas_Estados_Pedidos;
			}
			set
			{
				this._Fechas_Estados_Pedidos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Fechas_Estados_Pedidos(Fechas_Estados_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Estados_Pedido = this;
		}
		
		private void detach_Fechas_Estados_Pedidos(Fechas_Estados_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Estados_Pedido = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pedidos")]
	public partial class Pedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pedido_Id;
		
		private int _Cliente_Id;
		
		private bool _Enviar;
		
		private decimal _TotalACobrar;
		
		private decimal _AbonaCon;
		
		private EntitySet<Pedidos_Producto> _Pedidos_Productos;
		
		private EntitySet<Fechas_Estados_Pedido> _Fechas_Estados_Pedidos;
		
		private EntityRef<Cliente> _Cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPedido_IdChanging(int value);
    partial void OnPedido_IdChanged();
    partial void OnCliente_IdChanging(int value);
    partial void OnCliente_IdChanged();
    partial void OnEnviarChanging(bool value);
    partial void OnEnviarChanged();
    partial void OnTotalACobrarChanging(decimal value);
    partial void OnTotalACobrarChanged();
    partial void OnAbonaConChanging(decimal value);
    partial void OnAbonaConChanged();
    #endregion
		
		public Pedido()
		{
			this._Pedidos_Productos = new EntitySet<Pedidos_Producto>(new Action<Pedidos_Producto>(this.attach_Pedidos_Productos), new Action<Pedidos_Producto>(this.detach_Pedidos_Productos));
			this._Fechas_Estados_Pedidos = new EntitySet<Fechas_Estados_Pedido>(new Action<Fechas_Estados_Pedido>(this.attach_Fechas_Estados_Pedidos), new Action<Fechas_Estados_Pedido>(this.detach_Fechas_Estados_Pedidos));
			this._Cliente = default(EntityRef<Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pedido_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Pedido_Id
		{
			get
			{
				return this._Pedido_Id;
			}
			set
			{
				if ((this._Pedido_Id != value))
				{
					this.OnPedido_IdChanging(value);
					this.SendPropertyChanging();
					this._Pedido_Id = value;
					this.SendPropertyChanged("Pedido_Id");
					this.OnPedido_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cliente_Id", DbType="Int NOT NULL")]
		public int Cliente_Id
		{
			get
			{
				return this._Cliente_Id;
			}
			set
			{
				if ((this._Cliente_Id != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCliente_IdChanging(value);
					this.SendPropertyChanging();
					this._Cliente_Id = value;
					this.SendPropertyChanged("Cliente_Id");
					this.OnCliente_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enviar", DbType="Bit NOT NULL")]
		public bool Enviar
		{
			get
			{
				return this._Enviar;
			}
			set
			{
				if ((this._Enviar != value))
				{
					this.OnEnviarChanging(value);
					this.SendPropertyChanging();
					this._Enviar = value;
					this.SendPropertyChanged("Enviar");
					this.OnEnviarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalACobrar", DbType="Decimal(18,2) NOT NULL")]
		public decimal TotalACobrar
		{
			get
			{
				return this._TotalACobrar;
			}
			set
			{
				if ((this._TotalACobrar != value))
				{
					this.OnTotalACobrarChanging(value);
					this.SendPropertyChanging();
					this._TotalACobrar = value;
					this.SendPropertyChanged("TotalACobrar");
					this.OnTotalACobrarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AbonaCon", DbType="Decimal(18,2) NOT NULL")]
		public decimal AbonaCon
		{
			get
			{
				return this._AbonaCon;
			}
			set
			{
				if ((this._AbonaCon != value))
				{
					this.OnAbonaConChanging(value);
					this.SendPropertyChanging();
					this._AbonaCon = value;
					this.SendPropertyChanged("AbonaCon");
					this.OnAbonaConChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_Pedidos_Producto", Storage="_Pedidos_Productos", ThisKey="Pedido_Id", OtherKey="Pedido_Id")]
		public EntitySet<Pedidos_Producto> Pedidos_Productos
		{
			get
			{
				return this._Pedidos_Productos;
			}
			set
			{
				this._Pedidos_Productos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_Fechas_Estados_Pedido", Storage="_Fechas_Estados_Pedidos", ThisKey="Pedido_Id", OtherKey="Pedido_Id")]
		public EntitySet<Fechas_Estados_Pedido> Fechas_Estados_Pedidos
		{
			get
			{
				return this._Fechas_Estados_Pedidos;
			}
			set
			{
				this._Fechas_Estados_Pedidos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Pedido", Storage="_Cliente", ThisKey="Cliente_Id", OtherKey="Id", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Pedidos.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Pedidos.Add(this);
						this._Cliente_Id = value.Id;
					}
					else
					{
						this._Cliente_Id = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Pedidos_Productos(Pedidos_Producto entity)
		{
			this.SendPropertyChanging();
			entity.Pedido = this;
		}
		
		private void detach_Pedidos_Productos(Pedidos_Producto entity)
		{
			this.SendPropertyChanging();
			entity.Pedido = null;
		}
		
		private void attach_Fechas_Estados_Pedidos(Fechas_Estados_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Pedido = this;
		}
		
		private void detach_Fechas_Estados_Pedidos(Fechas_Estados_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Pedido = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Productos")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Prod_Cod;
		
		private string _Prod_Desc;
		
		private decimal _Prod_Precio;
		
		private bool _Prod_Web;
		
		private EntitySet<Pedidos_Producto> _Pedidos_Productos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProd_CodChanging(int value);
    partial void OnProd_CodChanged();
    partial void OnProd_DescChanging(string value);
    partial void OnProd_DescChanged();
    partial void OnProd_PrecioChanging(decimal value);
    partial void OnProd_PrecioChanged();
    partial void OnProd_WebChanging(bool value);
    partial void OnProd_WebChanged();
    #endregion
		
		public Producto()
		{
			this._Pedidos_Productos = new EntitySet<Pedidos_Producto>(new Action<Pedidos_Producto>(this.attach_Pedidos_Productos), new Action<Pedidos_Producto>(this.detach_Pedidos_Productos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prod_Cod", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Prod_Cod
		{
			get
			{
				return this._Prod_Cod;
			}
			set
			{
				if ((this._Prod_Cod != value))
				{
					this.OnProd_CodChanging(value);
					this.SendPropertyChanging();
					this._Prod_Cod = value;
					this.SendPropertyChanged("Prod_Cod");
					this.OnProd_CodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prod_Desc", DbType="NChar(80)")]
		public string Prod_Desc
		{
			get
			{
				return this._Prod_Desc;
			}
			set
			{
				if ((this._Prod_Desc != value))
				{
					this.OnProd_DescChanging(value);
					this.SendPropertyChanging();
					this._Prod_Desc = value;
					this.SendPropertyChanged("Prod_Desc");
					this.OnProd_DescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prod_Precio", DbType="Decimal(18,2) NOT NULL")]
		public decimal Prod_Precio
		{
			get
			{
				return this._Prod_Precio;
			}
			set
			{
				if ((this._Prod_Precio != value))
				{
					this.OnProd_PrecioChanging(value);
					this.SendPropertyChanging();
					this._Prod_Precio = value;
					this.SendPropertyChanged("Prod_Precio");
					this.OnProd_PrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prod_Web", DbType="Bit NOT NULL")]
		public bool Prod_Web
		{
			get
			{
				return this._Prod_Web;
			}
			set
			{
				if ((this._Prod_Web != value))
				{
					this.OnProd_WebChanging(value);
					this.SendPropertyChanging();
					this._Prod_Web = value;
					this.SendPropertyChanged("Prod_Web");
					this.OnProd_WebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Pedidos_Producto", Storage="_Pedidos_Productos", ThisKey="Prod_Cod", OtherKey="Producto_Cod")]
		public EntitySet<Pedidos_Producto> Pedidos_Productos
		{
			get
			{
				return this._Pedidos_Productos;
			}
			set
			{
				this._Pedidos_Productos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Pedidos_Productos(Pedidos_Producto entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Pedidos_Productos(Pedidos_Producto entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pedidos_Productos")]
	public partial class Pedidos_Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Pedido_Id;
		
		private int _Producto_Cod;
		
		private int _Cantidad_Producto;
		
		private EntityRef<Pedido> _Pedido;
		
		private EntityRef<Producto> _Producto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPedido_IdChanging(int value);
    partial void OnPedido_IdChanged();
    partial void OnProducto_CodChanging(int value);
    partial void OnProducto_CodChanged();
    partial void OnCantidad_ProductoChanging(int value);
    partial void OnCantidad_ProductoChanged();
    #endregion
		
		public Pedidos_Producto()
		{
			this._Pedido = default(EntityRef<Pedido>);
			this._Producto = default(EntityRef<Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pedido_Id", DbType="Int NOT NULL")]
		public int Pedido_Id
		{
			get
			{
				return this._Pedido_Id;
			}
			set
			{
				if ((this._Pedido_Id != value))
				{
					if (this._Pedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPedido_IdChanging(value);
					this.SendPropertyChanging();
					this._Pedido_Id = value;
					this.SendPropertyChanged("Pedido_Id");
					this.OnPedido_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Producto_Cod", DbType="Int NOT NULL")]
		public int Producto_Cod
		{
			get
			{
				return this._Producto_Cod;
			}
			set
			{
				if ((this._Producto_Cod != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProducto_CodChanging(value);
					this.SendPropertyChanging();
					this._Producto_Cod = value;
					this.SendPropertyChanged("Producto_Cod");
					this.OnProducto_CodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad_Producto", DbType="Int NOT NULL")]
		public int Cantidad_Producto
		{
			get
			{
				return this._Cantidad_Producto;
			}
			set
			{
				if ((this._Cantidad_Producto != value))
				{
					this.OnCantidad_ProductoChanging(value);
					this.SendPropertyChanging();
					this._Cantidad_Producto = value;
					this.SendPropertyChanged("Cantidad_Producto");
					this.OnCantidad_ProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_Pedidos_Producto", Storage="_Pedido", ThisKey="Pedido_Id", OtherKey="Pedido_Id", IsForeignKey=true)]
		public Pedido Pedido
		{
			get
			{
				return this._Pedido.Entity;
			}
			set
			{
				Pedido previousValue = this._Pedido.Entity;
				if (((previousValue != value) 
							|| (this._Pedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pedido.Entity = null;
						previousValue.Pedidos_Productos.Remove(this);
					}
					this._Pedido.Entity = value;
					if ((value != null))
					{
						value.Pedidos_Productos.Add(this);
						this._Pedido_Id = value.Pedido_Id;
					}
					else
					{
						this._Pedido_Id = default(int);
					}
					this.SendPropertyChanged("Pedido");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Pedidos_Producto", Storage="_Producto", ThisKey="Producto_Cod", OtherKey="Prod_Cod", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Pedidos_Productos.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Pedidos_Productos.Add(this);
						this._Producto_Cod = value.Prod_Cod;
					}
					else
					{
						this._Producto_Cod = default(int);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fechas_Estados_Pedidos")]
	public partial class Fechas_Estados_Pedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Estado_Id;
		
		private int _Pedido_Id;
		
		private System.DateTime _Fecha;
		
		private EntityRef<Estados_Pedido> _Estados_Pedido;
		
		private EntityRef<Pedido> _Pedido;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnEstado_IdChanging(int value);
    partial void OnEstado_IdChanged();
    partial void OnPedido_IdChanging(int value);
    partial void OnPedido_IdChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    #endregion
		
		public Fechas_Estados_Pedido()
		{
			this._Estados_Pedido = default(EntityRef<Estados_Pedido>);
			this._Pedido = default(EntityRef<Pedido>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado_Id", DbType="Int NOT NULL")]
		public int Estado_Id
		{
			get
			{
				return this._Estado_Id;
			}
			set
			{
				if ((this._Estado_Id != value))
				{
					if (this._Estados_Pedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEstado_IdChanging(value);
					this.SendPropertyChanging();
					this._Estado_Id = value;
					this.SendPropertyChanged("Estado_Id");
					this.OnEstado_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pedido_Id", DbType="Int NOT NULL")]
		public int Pedido_Id
		{
			get
			{
				return this._Pedido_Id;
			}
			set
			{
				if ((this._Pedido_Id != value))
				{
					if (this._Pedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPedido_IdChanging(value);
					this.SendPropertyChanging();
					this._Pedido_Id = value;
					this.SendPropertyChanged("Pedido_Id");
					this.OnPedido_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estados_Pedido_Fechas_Estados_Pedido", Storage="_Estados_Pedido", ThisKey="Estado_Id", OtherKey="Estado_Id", IsForeignKey=true)]
		public Estados_Pedido Estados_Pedido
		{
			get
			{
				return this._Estados_Pedido.Entity;
			}
			set
			{
				Estados_Pedido previousValue = this._Estados_Pedido.Entity;
				if (((previousValue != value) 
							|| (this._Estados_Pedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Estados_Pedido.Entity = null;
						previousValue.Fechas_Estados_Pedidos.Remove(this);
					}
					this._Estados_Pedido.Entity = value;
					if ((value != null))
					{
						value.Fechas_Estados_Pedidos.Add(this);
						this._Estado_Id = value.Estado_Id;
					}
					else
					{
						this._Estado_Id = default(int);
					}
					this.SendPropertyChanged("Estados_Pedido");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_Fechas_Estados_Pedido", Storage="_Pedido", ThisKey="Pedido_Id", OtherKey="Pedido_Id", IsForeignKey=true)]
		public Pedido Pedido
		{
			get
			{
				return this._Pedido.Entity;
			}
			set
			{
				Pedido previousValue = this._Pedido.Entity;
				if (((previousValue != value) 
							|| (this._Pedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pedido.Entity = null;
						previousValue.Fechas_Estados_Pedidos.Remove(this);
					}
					this._Pedido.Entity = value;
					if ((value != null))
					{
						value.Fechas_Estados_Pedidos.Add(this);
						this._Pedido_Id = value.Pedido_Id;
					}
					else
					{
						this._Pedido_Id = default(int);
					}
					this.SendPropertyChanged("Pedido");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
